version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./.deploy/default.conf:/etc/nginx/conf.d/default.conf
      # - ./.deploy/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html

