version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./.deploy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - experience
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-experience
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html
    networks:
      - experience
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_EXPERIENCE}
      MYSQL_USER: ${DB_USERNAME_EXPERIENCE}
      MYSQL_PASSWORD: ${DB_PASSWORD_EXPERIENCE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_EXPERIENCE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - experience
  redis:
    image: redis:alpine
    container_name: redis-experience
    command: redis-server
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - experience

networks:
  experience:
    driver: bridge
